spring:
  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: false

  datasource:
    url: jdbc:h2:file:./taxitest

  liquibase:
    change-log: db/changelog-test.yaml
    contexts: test

  h2:
    console:
      enabled: true
      path: /taxitest

server:
  port: 8081