spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxidev?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: db/changelog-dev.yaml
    contexts: dev

server:
  port: 8080